CREATE TABLE IF NOT EXISTS shortened_urls (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_url varchar(2048) NOT NULL,
    short_code varchar(10) NOT NULL,
    created_at_utc timestamp with time zone NOT NULL,
    last_accessed_at_utc timestamp with time zone NULL,
    visit_count bigint NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_shortened_urls_short_code
    ON shortened_urls (short_code);

CREATE INDEX IF NOT EXISTS ix_shortened_urls_original_url
    ON shortened_urls (original_url);